cmake_minimum_required(VERSION 3.16)
project(TuneSphere LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
include(FetchContent)
FetchContent_Declare(Asio GIT_REPOSITORY https://github.com/chriskohlhoff/asio.git GIT_TAG asio-1-30-2)
FetchContent_MakeAvailable(Asio)
set(ASIO_INCLUDE_DIR "${asio_SOURCE_DIR}/asio/include" CACHE PATH "Standalone Asio include directory")
FetchContent_Declare(Crow GIT_REPOSITORY https://github.com/CrowCpp/Crow.git GIT_TAG v1.2.1.2)
FetchContent_MakeAvailable(Crow)
add_executable(TuneSphere main.cpp server.cpp data_structures/CircularSongList.cpp services/SongService.cpp services/PlaylistService.cpp services/UserService.cpp services/SearchService.cpp routes/song_routes.cpp routes/playlist_routes.cpp routes/user_routes.cpp)
target_link_libraries(TuneSphere PRIVATE Crow::Crow)
target_compile_definitions(TuneSphere PRIVATE CROW_ENABLE_COMPRESSION)

if(WIN32)
	target_link_libraries(TuneSphere PRIVATE ws2_32 mswsock z)
endif()
